export const DummyCategories =
  [
    {
      id: '1',
      name: 'Vehicles',
      items: [
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Jeans',
          id: 'JeansCloths',
          quantity: 1,
          category: 'Vehicles',
          price: 5,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'Shirt',
          id: 'ShirtClothes',
          quantity: 1,
          category: 'Vehicles',
          price: 6,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Trousers',
          id: 'TrousersClothes',
          quantity: 1,
          category: 'Vehicles',
          price: 7,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'DressShirt',
          id: 'DressShirtClothes',
          quantity: 1,
          category: 'Vehicles',
          price: 20,
          isBooked: false,
          bookingDate: null,
        },
      ],
      sliderImage: [{image: '/assets/slide-images/clothes1.jpg'}, {image: '/assets/slide-images/clothes2.jpg'}]
    },
    {
      id: '2',
      name: 'Rooms',
      items: [
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Jeans',
          id: 'JeansCloths',
          quantity: 1,
          category: 'Rooms',
          price: 5,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'Shirt',
          id: 'ShirtClothes',
          quantity: 1,
          category: 'Rooms',
          price: 6,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Trousers',
          id: 'TrousersClothes',
          quantity: 1,
          category: 'Rooms',
          price: 7,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'DressShirt',
          id: 'DressShirtClothes',
          quantity: 1,
          category: 'Rooms',
          price: 20,
          isBooked: false,
          bookingDate: null,
        },
      ],
      sliderImage: [{image: '/assets/slide-images/clothes1.jpg'}, {image: '/assets/slide-images/clothes2.jpg'}]
    },
    {
      id: '3',
      name: 'Beamers',
      items: [
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Jeans',
          id: 'JeansCloths',
          quantity: 1,
          category: 'Beamers',
          price: 5,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'Shirt',
          id: 'ShirtClothes',
          quantity: 1,
          category: 'Beamers',
          price: 6,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes1.jpg',
          itemName: 'Trousers',
          id: 'TrousersClothes',
          quantity: 1,
          category: 'Beamers',
          price: 7,
          isBooked: false,
          bookingDate: null,
        },
        {
          imageUrl: '/assets/slide-images/clothes2.jpg',
          itemName: 'DressShirt',
          id: 'DressShirtClothes',
          quantity: 1,
          category: 'Beamers',
          price: 20,
          isBooked: false,
          bookingDate: null,
        },
      ],
      sliderImage: [{image: '/assets/slide-images/clothes1.jpg'}, {image: '/assets/slide-images/clothes2.jpg'}]
    }
  ];
